[build]
  base = "frontend"
  command = "npm install && npm run build" 
  publish = "dist" # The corrected path
  functions = "api/netlify/functions" 

# ----------------------------------------------------------------------
# API REDIRECT RULE (Allows React to talk to your Serverless Function)
# ----------------------------------------------------------------------
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# ----------------------------------------------------------------------
# SPA FALLBACK RULE (Crucial for fixing the "Page Not Found" on load)
# ----------------------------------------------------------------------
[[redirects]]
  from = "/*" # Match ALL remaining paths
  to = "/index.html" # Serve the main index file
  status = 200 # Proxy the request